#!/bin/bash
echo "This script assumes you placed this project folder in your machine."
echo "Run these commands inside frontend/ and mobile/ as needed."
echo ""
echo "Frontend:"
echo "  cd frontend"
echo "  cp ../.env.example .env.local"
echo "  npm install"
echo "  npm run dev"
echo ""
echo "Mobile:"
echo "  cd mobile"
echo "  cp ../.env.example .env"
echo "  npm install"
echo "  expo start"
